import {useEffect,useMemo,useState} from 'react'
import {MessageCircle,Send,Search} from 'lucide-react'
import {useSearchParams} from 'react-router-dom'
import {supabase} from '../lib/supabase'
export default function Chat({profile}){
 const [contacts,setContacts]=useState([]),[messages,setMessages]=useState([]),[selected,setSelected]=useState(null),[body,setBody]=useState(''),[q,setQ]=useState('');const [params]=useSearchParams()
 useEffect(()=>{loadContacts()},[])
 useEffect(()=>{if(selected)loadMessages(selected.id)},[selected?.id])
 useEffect(()=>{if(!profile?.id)return;const ch=supabase.channel(`chat-${profile.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages'},p=>{if(p.new.sender_id===selected?.id||p.new.recipient_id===selected?.id)loadMessages(selected.id)}).subscribe();return()=>supabase.removeChannel(ch)},[profile?.id,selected?.id])
 async function loadContacts(){const {data}=await supabase.rpc('list_chat_contacts');setContacts(data||[]);const wanted=params.get('user');const first=(data||[]).find(x=>x.id===wanted)||(data||[])[0];if(first)setSelected(first)}
 async function loadMessages(uid){const {data}=await supabase.from('chat_messages').select('*').or(`and(sender_id.eq.${profile.id},recipient_id.eq.${uid}),and(sender_id.eq.${uid},recipient_id.eq.${profile.id})`).order('created_at',{ascending:true}).limit(300);setMessages(data||[]);await supabase.from('chat_messages').update({read_at:new Date().toISOString()}).eq('sender_id',uid).eq('recipient_id',profile.id).is('read_at',null)}
 async function send(e){e.preventDefault();if(!selected||!body.trim())return;const text=body;setBody('');const {error}=await supabase.rpc('send_chat_message',{p_recipient_id:selected.id,p_body:text});if(error)alert(error.message);else loadMessages(selected.id)}
 const filtered=useMemo(()=>contacts.filter(c=>`${c.full_name} ${c.lgu_name||''} ${c.role}`.toLowerCase().includes(q.toLowerCase())),[contacts,q])
 return <><div className="page-head"><div><span className="eyebrow">Internal Coordination</span><h1>DROMIC Chat</h1><p>Direct messaging between approved LGU, PSWDO, DSWD/PDRRMO and administrator accounts.</p></div></div><div className="chat-shell panel"><aside className="chat-contacts"><div className="searchbox compact"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people or LGU"/></div>{filtered.map(c=><button key={c.id} className={selected?.id===c.id?'active':''} onClick={()=>setSelected(c)}><div className="mini-avatar">{c.avatar_url?<img src={c.avatar_url}/>:c.full_name?.slice(0,1)||'U'}</div><div><b>{c.full_name||c.email}</b><small>{c.lgu_name||c.role.toUpperCase()}</small></div></button>)}</aside><section className="chat-main">{selected?<><header><MessageCircle size={19}/><div><b>{selected.full_name}</b><small>{selected.lgu_name||selected.role}</small></div></header><div className="chat-messages">{messages.map(m=><div key={m.id} className={m.sender_id===profile.id?'chat-bubble mine':'chat-bubble'}><span>{m.body}</span><small>{new Date(m.created_at).toLocaleString()}</small></div>)}{!messages.length&&<div className="empty">No messages yet. Start the conversation.</div>}</div><form className="chat-compose" onSubmit={send}><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message…" maxLength={2000}/><button className="btn primary"><Send size={16}/>Send</button></form></>:<div className="empty-state">Select a user to start chatting.</div>}</section></div></>
}
