import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import StatusBadge from '../components/StatusBadge'
import DromicSummaryTable from '../components/DromicSummaryTable'
import {ChevronDown,ChevronUp} from 'lucide-react'
export default function History({profile}){
 const [rows,setRows]=useState([]),[q,setQ]=useState(''),[expanded,setExpanded]=useState(null),[versions,setVersions]=useState([]),[versionRows,setVersionRows]=useState({})
 useEffect(()=>{load()},[])
 async function load(){let query=supabase.from('reports').select('*,lgus(name),incidents(name),reporting_cycles(sitrep_number,cutoff_at)').order('updated_at',{ascending:false}).limit(300);if(profile.role==='lgu')query=query.eq('lgu_id',profile.lgu_id);const {data}=await query;setRows(data||[])}
 async function toggle(r){if(expanded===r.id){setExpanded(null);return}setExpanded(r.id);const {data:v}=await supabase.from('report_versions').select('*').eq('report_id',r.id).order('version_number',{ascending:false});setVersions(v||[]);const map={};for(const x of v||[]){const {data:b}=await supabase.from('report_version_barangays').select('*,barangays(*)').eq('report_version_id',x.id);map[x.id]=(b||[]).map(z=>({...z,data:z.data_snapshot,barangay:z.barangays,barangay_name:z.barangays?.name}))}setVersionRows(map)}
 const filtered=rows.filter(r=>`${r.lgus?.name} ${r.incidents?.name} ${r.status}`.toLowerCase().includes(q.toLowerCase()))
 return <><div className="page-head"><div><span className="eyebrow">Historical Records</span><h1>Report & Version History</h1><p>Every submission is retained. Changed updates never erase the LGU's earlier submitted tables.</p></div><input className="search-input" placeholder="Search incident, LGU or status" value={q} onChange={e=>setQ(e.target.value)}/></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>LGU</th><th>Incident</th><th>SitRep</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.lgus?.name}</td><td>{r.incidents?.name}</td><td>{r.reporting_cycles?.sitrep_number}</td><td><StatusBadge status={r.status}/></td><td>{new Date(r.updated_at).toLocaleString()}</td><td><button className="text-btn" onClick={()=>toggle(r)}>{expanded===r.id?<><ChevronUp size={15}/>Hide versions</>:<><ChevronDown size={15}/>View versions</>}</button></td></tr>)}</tbody></table></div></section>{expanded&&<section className="version-history"><h2>Submitted versions</h2>{versions.map(v=><details key={v.id} className="panel version-card"><summary><div><b>Version {v.version_number}</b><span>{v.header_snapshot?.no_change?'NO CHANGE • ':''}{v.status} • {new Date(v.submitted_at).toLocaleString()}</span></div></summary><DromicSummaryTable singleLguName={rows.find(r=>r.id===expanded)?.lgus?.name||'LGU'} singleBarangays={versionRows[v.id]||[]} defaultDetail title={`Version ${v.version_number} table`}/></details>)}{!versions.length&&<div className="panel empty">No submitted versions yet.</div>}</section>}</>
}
