import {useEffect,useState} from 'react'
import {BellRing,CalendarPlus,Plus,Power,Archive} from 'lucide-react'
import {supabase} from '../lib/supabase'
export default function Operations(){
 const [incidents,setIncidents]=useState([]),[notice,setNotice]=useState(''),[form,setForm]=useState({name:'',type:'Typhoon',start_date:new Date().toISOString().slice(0,10),description:''}),[cycle,setCycle]=useState({incident_id:'',sitrep_number:1,cutoff_at:'',deadline_at:''})
 useEffect(()=>{load()},[])
 async function load(){const {data}=await supabase.from('incidents').select('*').order('start_date',{ascending:false});setIncidents(data||[])}
 async function createIncident(e){e.preventDefault();const {data,error}=await supabase.from('incidents').insert({...form,status:'ACTIVE'}).select().single();if(error)return setNotice(error.message);setCycle(x=>({...x,incident_id:data.id}));setForm({...form,name:'',description:''});setNotice('Incident created.');load()}
 async function setIncidentStatus(id,status){if(!confirm(`${status==='ACTIVE'?'Reactivate':'Set'} this incident as ${status}?`))return;const {error}=await supabase.from('incidents').update({status}).eq('id',id);if(error)return setNotice(error.message);setNotice(`Incident is now ${status.toLowerCase()}.`);load()}
 async function createCycle(e){e.preventDefault();const payload={incident_id:cycle.incident_id,sitrep_number:Number(cycle.sitrep_number),reporting_date:cycle.cutoff_at.slice(0,10),cutoff_at:new Date(cycle.cutoff_at).toISOString(),deadline_at:cycle.deadline_at?new Date(cycle.deadline_at).toISOString():null,status:'OPEN'};const {error}=await supabase.from('reporting_cycles').insert(payload);if(error)return setNotice(error.message);setNotice('SitRep cycle opened.');setCycle({...cycle,sitrep_number:Number(cycle.sitrep_number)+1,cutoff_at:'',deadline_at:''})}
 return <><div className="page-head"><div><span className="eyebrow">Incident Management</span><h1>Incidents & Reporting Cycles</h1><p>Create, close, inactivate and reopen disaster incidents without mixing them with account management.</p></div></div>{notice&&<div className="alert blue">{notice}</div>}
 <div className="split"><section className="panel glass-panel"><h2><Plus size={18}/> New incident</h2><form className="stack" onSubmit={createIncident}><label>Incident name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Typhoon</option><option>Habagat</option><option>Flooding</option><option>Earthquake</option><option>Fire</option><option>Combined Weather Event</option><option>Other</option></select></label><label>Start date<input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn primary"><BellRing size={16}/>Create incident</button></form></section>
 <section className="panel glass-panel"><h2><CalendarPlus size={18}/> Open SitRep cycle</h2><form className="stack" onSubmit={createCycle}><label>Active incident<select required value={cycle.incident_id} onChange={e=>setCycle({...cycle,incident_id:e.target.value})}><option value="">Select incident</option>{incidents.filter(i=>i.status==='ACTIVE').map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>SitRep number<input type="number" min="1" value={cycle.sitrep_number} onChange={e=>setCycle({...cycle,sitrep_number:e.target.value})}/></label><label>Reporting cut-off<input type="datetime-local" required value={cycle.cutoff_at} onChange={e=>setCycle({...cycle,cutoff_at:e.target.value})}/></label><label>LGU deadline<input type="datetime-local" value={cycle.deadline_at} onChange={e=>setCycle({...cycle,deadline_at:e.target.value})}/></label><button className="btn primary">Open reporting cycle</button></form></section></div>
 <section className="panel glass-panel"><div className="panel-head"><div><h2>Incident registry</h2><p>Closed and inactive incidents remain available for historical reports.</p></div></div><div className="table-wrap"><table><thead><tr><th>Incident</th><th>Start</th><th>Status</th><th>Actions</th></tr></thead><tbody>{incidents.map(i=><tr key={i.id}><td><b>{i.name}</b><small>{i.type}</small></td><td>{i.start_date}</td><td><span className={'badge '+(i.status==='ACTIVE'?'green':'gray')}>{i.status}</span></td><td><div className="row-actions">{i.status!=='ACTIVE'&&<button className="btn secondary" onClick={()=>setIncidentStatus(i.id,'ACTIVE')}><Power size={15}/>Reactivate</button>}{i.status==='ACTIVE'&&<><button className="btn secondary" onClick={()=>setIncidentStatus(i.id,'CLOSED')}><Archive size={15}/>Close</button><button className="btn secondary" onClick={()=>setIncidentStatus(i.id,'INACTIVE')}>Inactivate</button></>}</div></td></tr>)}</tbody></table></div></section></>
}