import {useEffect,useState} from 'react'
import {AtSign,Camera,Phone,Save,UserRound} from 'lucide-react'
import {supabase} from '../lib/supabase'
export default function Profile({profile,onProfileUpdated}){
 const [form,setForm]=useState({full_name:'',office_position:'',contact_number:'',avatar_url:''});const [saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>setForm({full_name:profile?.full_name||'',office_position:profile?.office_position||'',contact_number:profile?.contact_number||'',avatar_url:profile?.avatar_url||''}),[profile])
 async function upload(file){if(!file)return;if(file.size>3*1024*1024)return setError('Profile photo must be 3 MB or smaller.');setUploading(true);setError('');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${profile.id}/avatar.${ext}`;const {error}=await supabase.storage.from('profile-photos').upload(path,file,{upsert:true,contentType:file.type});if(error){setUploading(false);return setError(error.message)}const {data}=supabase.storage.from('profile-photos').getPublicUrl(path);setForm(f=>({...f,avatar_url:`${data.publicUrl}?v=${Date.now()}`}));setUploading(false);setMessage('Photo uploaded. Click Save profile to apply it.')}
 async function save(e){e.preventDefault();setMessage('');setError('');if(!form.full_name.trim())return setError('Full name is required.');if(!form.contact_number.trim())return setError('Contact number is required.');setSaving(true);const {data,error}=await supabase.rpc('update_my_contact_profile',{p_full_name:form.full_name.trim(),p_office_position:form.office_position.trim(),p_contact_number:form.contact_number.trim(),p_avatar_url:form.avatar_url||null});setSaving(false);if(error)return setError(error.message);setMessage('Profile updated successfully.');onProfileUpdated?.(data)}
 return <><div className="page-head"><div><span className="eyebrow">Account & Contact</span><h1>My Profile</h1><p>Add a profile photo and keep contact details current for faster coordination.</p></div></div>{error&&<div className="alert red">{error}</div>}{message&&<div className="alert green">{message}</div>}<section className="panel profile-panel"><form className="profile-form" onSubmit={save}><div className="profile-photo-editor"><div className="profile-avatar">{form.avatar_url?<img src={form.avatar_url} alt="Profile"/>:<UserRound size={44}/>}</div><label className="btn secondary file-button"><Camera size={16}/>{uploading?'Uploading…':'Change profile photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label><small>JPG, PNG or WebP • maximum 3 MB</small></div><label>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Office / Position<input value={form.office_position} onChange={e=>setForm({...form,office_position:e.target.value})}/></label><label>Email address<div className="readonly-contact"><AtSign size={16}/><span>{profile?.email||'No email recorded'}</span></div></label><label>Contact number<div className="input-with-icon"><Phone size={16}/><input required inputMode="tel" placeholder="e.g., 0917 123 4567" value={form.contact_number} onChange={e=>setForm({...form,contact_number:e.target.value})}/></div></label><button className="btn primary profile-save" disabled={saving||uploading}><Save size={16}/>{saving?'Saving…':'Save profile'}</button></form></section></>
}
