import {useEffect,useMemo,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {Search,RefreshCw,Eye,X,Users,Home,Building2,PackageOpen} from 'lucide-react'
import {supabase} from '../lib/supabase'
import StatCard from '../components/StatCard';import StatusBadge from '../components/StatusBadge'
const n=v=>Number(v||0)
export default function ProvincialDashboard(){
 const [incident,setIncident]=useState(null),[cycle,setCycle]=useState(null),[lgus,setLgus]=useState([]),[reports,setReports]=useState([]),[metrics,setMetrics]=useState({}),[relief,setRelief]=useState({}),[q,setQ]=useState(''),[status,setStatus]=useState('ALL'),[detail,setDetail]=useState(null);const nav=useNavigate();useEffect(()=>{load()},[])
 async function load(){
  const {data:i}=await supabase.from('incidents').select('*').eq('status','ACTIVE').order('start_date',{ascending:false}).limit(1).maybeSingle();setIncident(i)
  const {data:l}=await supabase.from('lgus').select('*').eq('active',true).order('name');setLgus(l||[])
  if(!i){setReports([]);setCycle(null);return}
  const {data:c}=await supabase.from('reporting_cycles').select('*').eq('incident_id',i.id).eq('status','OPEN').order('cutoff_at').limit(1).maybeSingle();setCycle(c)
  if(!c){setReports([]);return}
  const {data:r}=await supabase.from('reports').select('*').eq('reporting_cycle_id',c.id);setReports(r||[])
  const ids=(r||[]).map(x=>x.id);const m={}
  if(ids.length){const {data:b}=await supabase.from('barangay_reports').select('report_id,data').in('report_id',ids);(b||[]).forEach(x=>{const z=m[x.report_id]||(m[x.report_id]={affectedFamilies:0,affectedPersons:0,openEcs:0});z.affectedFamilies+=n(x.data?.affected_families);z.affectedPersons+=n(x.data?.affected_persons);z.openEcs+=n(x.data?.evacuation_centers_now)})}setMetrics(m)
  const {data:t}=await supabase.from('relief_transactions').select('lgu_id,quantity,distribution_date,relief_items(name)').eq('incident_id',i.id).eq('transaction_type','RELEASED_TO_LGU');const rr={};(t||[]).forEach(x=>{if(!x.lgu_id)return;const z=rr[x.lgu_id]||(rr[x.lgu_id]={ffp:0,other:0,last:null});if((x.relief_items?.name||'').toLowerCase().includes('family food'))z.ffp+=n(x.quantity);else z.other+=n(x.quantity);if(!z.last||x.distribution_date>z.last)z.last=x.distribution_date});setRelief(rr)
 }
 const rows=useMemo(()=>lgus.map(l=>{const report=reports.find(r=>r.lgu_id===l.id);return {lgu:l,report,m:metrics[report?.id]||{},relief:relief[l.id]||{}}}),[lgus,reports,metrics,relief])
 const filtered=rows.filter(x=>x.lgu.name.toLowerCase().includes(q.toLowerCase())&&(status==='ALL'||(status==='NO_REPORT'?!x.report:x.report?.status===status)));const count=s=>rows.filter(x=>s==='NO_REPORT'?!x.report:x.report?.status===s).length
 const totals=rows.reduce((a,x)=>({families:a.families+n(x.m.affectedFamilies),persons:a.persons+n(x.m.affectedPersons),ecs:a.ecs+n(x.m.openEcs),ffp:a.ffp+n(x.relief.ffp)}),{families:0,persons:0,ecs:0,ffp:0})
 const high=rows.filter(x=>x.report).sort((a,b)=>(n(b.m.affectedFamilies)+n(b.m.affectedPersons)+n(b.m.openEcs))-(n(a.m.affectedFamilies)+n(a.m.affectedPersons)+n(a.m.openEcs))).slice(0,8);const max=Math.max(1,...high.map(x=>n(x.m.affectedFamilies)))
 function openDetail(kind,title){let list=rows;if(kind==='SUBMITTED')list=rows.filter(x=>['SUBMITTED','RESUBMITTED'].includes(x.report?.status));else if(kind==='ALL')list=rows;else if(kind==='NO_REPORT')list=rows.filter(x=>!x.report);else list=rows.filter(x=>x.report?.status===kind);setDetail({title,list})}
 return <><div className="page-head"><div><span className="eyebrow">Province-wide Monitoring</span><h1>{incident?.name||'No active incident'}</h1><p>{cycle?`Situation Report No. ${cycle.sitrep_number} • Cut-off ${new Date(cycle.cutoff_at).toLocaleString()}`:'No open reporting cycle.'}</p></div><button className="btn secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div>
 <div className="stats operational-stats"><div className="stat glass-panel"><Users/><small>Affected Families</small><strong>{totals.families.toLocaleString()}</strong></div><div className="stat glass-panel"><Home/><small>Affected Individuals</small><strong>{totals.persons.toLocaleString()}</strong></div><div className="stat glass-panel"><Building2/><small>Open ECs</small><strong>{totals.ecs.toLocaleString()}</strong></div><div className="stat glass-panel"><PackageOpen/><small>FFPs Delivered</small><strong>{totals.ffp.toLocaleString()}</strong></div></div>
 {high.length>0&&<section className="panel glass-panel"><div className="panel-head"><div><h2>LGU impact overview</h2><p>Transparent operational indicators from the current reporting cycle.</p></div></div><div className="impact-chart">{high.map(x=><div className="impact-row" key={x.lgu.id}><b>{x.lgu.name}</b><div className="bar-track"><span style={{width:`${Math.max(3,n(x.m.affectedFamilies)/max*100)}%`}}/></div><div className="impact-values"><span>{n(x.m.affectedFamilies).toLocaleString()} families</span><span>{n(x.m.affectedPersons).toLocaleString()} people</span><span>{n(x.m.openEcs)} open ECs</span></div></div>)}</div></section>}
 <div className="stats compact-stats"><StatCard label="Configured LGUs" value={lgus.length} onClick={()=>openDetail('ALL','Configured LGUs')}/><StatCard label="Submitted / Resubmitted" value={count('SUBMITTED')+count('RESUBMITTED')} tone="yellow" onClick={()=>openDetail('SUBMITTED','Submitted / Resubmitted LGUs')}/><StatCard label="Validated" value={count('VALIDATED')} tone="green" onClick={()=>openDetail('VALIDATED','Validated LGUs')}/><StatCard label="Pending" value={count('NO_REPORT')} tone="gray" onClick={()=>openDetail('NO_REPORT','LGUs with no report')}/></div>
 {detail&&<section className="panel stat-detail"><div className="panel-head"><div><h2>{detail.title}</h2><p>{detail.list.length} matching LGUs.</p></div><button className="icon" onClick={()=>setDetail(null)}><X size={18}/></button></div><div className="chip-list">{detail.list.map(({lgu,report})=><button key={lgu.id} className="detail-chip" onClick={()=>report&&nav(`/review/${report.id}`)}><b>{lgu.name}</b><StatusBadge status={report?.status||'NO_REPORT'}/></button>)}</div></section>}
 <section className="panel glass-panel"><div className="panel-head"><div><h2>LGU operational monitor</h2><p>Reporting status, disaster impact and relief deliveries in one view.</p></div><div className="filters"><div className="searchbox compact"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search LGU"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="NO_REPORT">No report</option><option value="SUBMITTED">Submitted</option><option value="RESUBMITTED">Resubmitted</option><option value="RETURNED_FOR_CORRECTION">Returned</option><option value="VALIDATED">Validated</option></select></div></div><div className="table-wrap"><table><thead><tr><th>LGU</th><th>Status</th><th>Affected Families</th><th>Individuals</th><th>Open ECs</th><th>FFPs Received</th><th>Other Goods</th><th>Latest Delivery</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.lgu.id}><td><b>{x.lgu.name}</b></td><td><StatusBadge status={x.report?.status||'NO_REPORT'}/></td><td>{n(x.m.affectedFamilies).toLocaleString()}</td><td>{n(x.m.affectedPersons).toLocaleString()}</td><td>{n(x.m.openEcs)}</td><td>{n(x.relief.ffp).toLocaleString()}</td><td>{n(x.relief.other).toLocaleString()}</td><td>{x.relief.last||'—'}</td><td>{x.report&&<button className="icon" onClick={()=>nav(`/review/${x.report.id}`)}><Eye size={17}/></button>}</td></tr>)}</tbody></table></div></section></>
}