import {useEffect,useMemo,useState} from 'react';import {PackageCheck,Search,Truck} from 'lucide-react';import {supabase} from '../lib/supabase'
export default function ReliefTracking(){
 const [items,setItems]=useState([]),[lgus,setLgus]=useState([]),[incidents,setIncidents]=useState([]),[tx,setTx]=useState([]),[q,setQ]=useState(''),[form,setForm]=useState({item_id:'',lgu_id:'',incident_id:'',transaction_type:'RELEASED_TO_LGU',quantity:1,distribution_date:new Date().toISOString().slice(0,10),reference_no:'',recipient:'',remarks:''})
 async function load(){const [{data:a},{data:l},{data:i},{data:t}]=await Promise.all([supabase.from('relief_stock_summary').select('*').order('name'),supabase.from('lgus').select('*').eq('active',true).order('name'),supabase.from('incidents').select('*').order('start_date',{ascending:false}),supabase.from('relief_transactions').select('*,relief_items(name,unit),lgus(name),incidents(name)').order('distribution_date',{ascending:false}).limit(250)]);setItems(a||[]);setLgus(l||[]);setIncidents(i||[]);setTx(t||[])}useEffect(()=>{load()},[])
 async function save(e){e.preventDefault();const {error}=await supabase.from('relief_transactions').insert({...form,quantity:Number(form.quantity),lgu_id:form.lgu_id||null,incident_id:form.incident_id||null});if(error)return alert(error.message);setForm({...form,quantity:1,reference_no:'',recipient:'',remarks:''});load()}
 const deliveries=useMemo(()=>tx.filter(x=>x.transaction_type==='RELEASED_TO_LGU'&&(!q||x.lgus?.name?.toLowerCase().includes(q.toLowerCase()))),[tx,q])
 return <><div className="page-head"><div><span className="eyebrow">Relief Logistics</span><h1>Relief Inventory</h1><p>See provincial stock, record LGU deliveries, and track exactly what each LGU received and when.</p></div></div>
 <div className="stats">{items.map(x=><div className="stat glass-panel" key={x.id}><small>{x.name}</small><strong>{Number(x.available||0).toLocaleString()}</strong><span>{x.unit} available</span></div>)}</div>
 <div className="split"><section className="panel glass-panel"><h2><Truck size={18}/> Record movement</h2><form className="stack" onSubmit={save}><label>Movement<select value={form.transaction_type} onChange={e=>setForm({...form,transaction_type:e.target.value})}><option value="RECEIVED">Stock received</option><option value="RELEASED_TO_LGU">Delivered to LGU</option><option value="DISTRIBUTED">Distributed / acknowledged</option><option value="ADJUSTMENT">Inventory adjustment</option></select></label><label>Item<select required value={form.item_id} onChange={e=>setForm({...form,item_id:e.target.value})}><option value="">Select item</option>{items.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Quantity<input type="number" min="1" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Recipient LGU<select value={form.lgu_id} onChange={e=>setForm({...form,lgu_id:e.target.value})}><option value="">Provincial stock / none</option>{lgus.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Incident<select value={form.incident_id} onChange={e=>setForm({...form,incident_id:e.target.value})}><option value="">None</option>{incidents.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Date received / delivered<input type="date" value={form.distribution_date} onChange={e=>setForm({...form,distribution_date:e.target.value})}/></label><label>Receiving officer<input value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value})}/></label><label>Reference no.<input value={form.reference_no} onChange={e=>setForm({...form,reference_no:e.target.value})}/></label><label>Remarks<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><button className="btn primary"><PackageCheck size={16}/>Save movement</button></form></section>
 <section className="panel glass-panel"><div className="panel-head"><div><h2>LGU delivery tracker</h2><p>Latest relief goods delivered to local governments.</p></div><div className="searchbox compact"><Search size={16}/><input placeholder="Search LGU" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>LGU</th><th>Item</th><th>Quantity</th><th>Incident</th><th>Received by</th></tr></thead><tbody>{deliveries.map(x=><tr key={x.id}><td><b>{x.distribution_date}</b></td><td>{x.lgus?.name||'—'}</td><td>{x.relief_items?.name}</td><td><b>{Number(x.quantity).toLocaleString()}</b> {x.relief_items?.unit}</td><td>{x.incidents?.name||'—'}</td><td>{x.recipient||'—'}</td></tr>)}</tbody></table></div></section></div></>
}