import { useEffect,useState } from 'react'
import { Plus,FileSpreadsheet,FileText,LockKeyhole,Send,RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { exportSitRepPdf,exportSitRepXlsx } from '../lib/exporters'
import DromicSummaryTable from '../components/DromicSummaryTable'
export default function SitReps({profile}){
 const [incident,setIncident]=useState(null),[cycles,setCycles]=useState([]),[sitReps,setSitReps]=useState([]),[selected,setSelected]=useState(null),[entries,setEntries]=useState([])
 const canManage=['pswdo','admin'].includes(profile?.role)
 useEffect(()=>{load()},[])
 async function load(){const {data:i}=await supabase.from('incidents').select('*').eq('status','ACTIVE').order('start_date',{ascending:false}).limit(1).maybeSingle();setIncident(i);if(!i)return;const [{data:c},{data:s}]=await Promise.all([supabase.from('reporting_cycles').select('*').eq('incident_id',i.id).order('sitrep_number',{ascending:false}),supabase.from('sitreps').select('*').eq('incident_id',i.id).order('sitrep_number',{ascending:false})]);setCycles(c||[]);setSitReps(s||[]);if(selected){const match=(s||[]).find(x=>x.id===selected.id);if(match)await open(match.id)}}
 async function create(cycle){const {data,error}=await supabase.rpc('create_sitrep_from_cycle',{p_cycle_id:cycle.id,p_prepared_by:profile.full_name});if(error)alert(error.message);else{await load();open(data.id)}}
 async function open(id){const {data:s}=await supabase.from('sitreps').select('*').eq('id',id).single();setSelected(s);const {data:e,error}=await supabase.rpc('get_sitrep_consolidation',{p_sitrep_id:id});if(error)alert(error.message);else setEntries(e||[])}
 async function finalize(){if(!confirm('Finalize this SitRep? The exact included LGU versions will be locked and later validations will not alter it.'))return;const {error}=await supabase.rpc('finalize_sitrep',{p_sitrep_id:selected.id});if(error)alert(error.message);else{await open(selected.id);load()}}
 async function distribute(){const raw=prompt('Recipients (comma-separated), e.g. DSWD FO1, PDRRMO');if(!raw)return;const recipients=raw.split(',').map(x=>x.trim()).filter(Boolean);const {data,error}=await supabase.rpc('distribute_sitrep',{p_sitrep_id:selected.id,p_recipients:recipients,p_method:'SECURE_ACCESS'});if(error)alert(error.message);else{alert(`${data} distribution record(s) saved.`);open(selected.id);load()}}
 return <><div className="page-head"><div><span className="eyebrow">Provincial Consolidation</span><h1>PSWDO Main DROMIC Report</h1><p>Validated LGU reports are automatically added to the current DRAFT consolidation.</p></div><button className="btn secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="split"><section className="panel"><h2>Reporting cycles</h2>{cycles.map(c=><div className="cycle-row" key={c.id}><div><b>SitRep {c.sitrep_number}</b><small>Cut-off {new Date(c.cutoff_at).toLocaleString()}</small></div>{sitReps.find(s=>s.reporting_cycle_id===c.id)?<button className="text-btn" onClick={()=>open(sitReps.find(s=>s.reporting_cycle_id===c.id).id)}>Open consolidated report</button>:canManage?<button className="btn small primary" onClick={()=>create(c)}><Plus size={14}/>Create main report</button>:<span>Not yet generated</span>}</div>)}</section><section className="panel sitrep-preview">{selected?<><div className="panel-head"><div><h2>SitRep {selected.sitrep_number}</h2><p>{selected.status} • {entries.length} validated LGU{entries.length===1?'':'s'} included</p></div></div><div className="actions"><button className="btn secondary" onClick={()=>exportSitRepXlsx({sitrep:selected,incident,entries})}><FileSpreadsheet size={16}/>Excel</button><button className="btn secondary" onClick={()=>exportSitRepPdf({sitrep:selected,incident,entries})}><FileText size={16}/>PDF</button>{canManage&&selected.status==='DRAFT'&&<button className="btn primary" onClick={finalize}><LockKeyhole size={16}/>Finalize</button>}{canManage&&['FINALIZED','DISTRIBUTED'].includes(selected.status)&&<button className="btn primary" onClick={distribute}><Send size={16}/>Distribute</button>}</div><div className={`consolidation-state ${selected.status==='DRAFT'?'live-draft':'locked'}`}><b>{selected.status==='DRAFT'?'Live consolidation':'Locked consolidation'}</b><span>{selected.status==='DRAFT'?'Newly validated LGUs are added automatically.':'This finalized report will no longer change when later LGU reports are validated.'}</span></div></>:<div className="empty-state"><b>Select or create a reporting cycle.</b><span>The PSWDO main table will contain all validated LGUs.</span></div>}</section></div>{selected&&<DromicSummaryTable entries={entries} title={`Consolidated DROMIC Table — SitRep ${selected.sitrep_number}`}/>}</>
}
