import { useMemo,useState } from 'react'
import { ChevronDown, ChevronRight, Trash2, AlertTriangle } from 'lucide-react'
import { CORE_GROUPS,DROMIC_FIELDS,GROUPS } from '../data/dromicFields'
import FieldInput from './FieldInput'
import { validateBarangay,computedTotals } from '../lib/validators'
export default function BarangayEditor({item,previous,onChange,onRemove,disabled}){
 const [expanded,setExpanded]=useState(true),[full,setFull]=useState(false)
 const issues=useMemo(()=>validateBarangay(item.data||{},previous||{}),[item.data,previous]); const groups=full?GROUPS:CORE_GROUPS; const totals=computedTotals(item.data||{})
 const update=(key,value)=>{const d={...(item.data||{}),[key]:value}; const f=DROMIC_FIELDS.find(x=>x.key===key); if(f?.computedFrom){const [a,b]=f.computedFrom; d[key]=Number(d[a]||0)*Number(d[b]||0)} onChange({...item,data:d})}
 return <section className="barangay-card"><div className="barangay-head"><button className="fold" onClick={()=>setExpanded(!expanded)}>{expanded?<ChevronDown/>:<ChevronRight/>}</button><div><b>{item.barangay?.name||item.barangay_name||'Barangay'}</b><small>{issues.length?`${issues.length} validation issue${issues.length>1?'s':''}`:'Ready for review'}</small></div>{issues.length>0&&<span className="issue-pill"><AlertTriangle size={14}/>{issues.filter(x=>x.severity==='RED').length} errors</span>}<button className="icon danger" disabled={disabled} onClick={onRemove}><Trash2 size={16}/></button></div>{expanded&&<div className="barangay-body"><div className="computed-strip"><span>Total displaced families NOW <b>{totals.total_displaced_families_now}</b></span><span>Total displaced persons NOW <b>{totals.total_displaced_persons_now}</b></span><span>Damaged houses <b>{totals.damaged_houses_total}</b></span></div><button className="text-btn" onClick={()=>setFull(!full)}>{full?'Show essential fields only':'Show full DROMIC fields'}</button>{groups.map(group=><details key={group} open={['Number of Affected','Number of Displaced','Damaged Houses'].includes(group)} className="field-group"><summary>{group}</summary><div className="field-grid">{DROMIC_FIELDS.filter(f=>f.group===group).map(field=><FieldInput key={field.key} field={field} value={item.data?.[field.key]} onChange={update} disabled={disabled} issue={issues.find(i=>i.field===field.key)}/>)}</div></details>)}{issues.length>0&&<div className="validation-box"><b>Validation summary</b>{issues.map((x,i)=><div key={i} className={`validation-line ${x.severity.toLowerCase()}`}>{x.severity}: {x.message}</div>)}</div>}</div>}</section>
}
