import { useMemo,useState } from 'react'
import { AlertTriangle,LayoutGrid,Rows3 } from 'lucide-react'
import { DROMIC_FIELDS } from '../data/dromicFields'
import { validateBarangay } from '../lib/validators'

const CORE_KEYS=['affected_families','affected_persons','affected_4ps_families','evacuation_centers_cum','evacuation_centers_now','ec_latitude','ec_longitude','ec_name','ec_address','origin_brgy_name','origin_brgy_count','inside_families_cum','inside_families_now','inside_persons_cum','inside_persons_now','outside_families_cum','outside_families_now','outside_persons_cum','outside_persons_now','non_idp_families','non_idp_persons','damaged_totally','damaged_partially','province_served','province_amount','lgu_served','lgu_amount','ngo_amount','others_amount','remarks']
const TABS=[['core','Official Core Table',CORE_KEYS],['sadd','SADD / Vulnerable Sectors',DROMIC_FIELDS.filter(f=>['Sex & Age Distribution','Vulnerable Sectors'].includes(f.group)).map(f=>f.key)],['facilities','EC Facilities / Tents',DROMIC_FIELDS.filter(f=>['Evacuation Center Facilities','Tents Deployed'].includes(f.group)).map(f=>f.key)],['assistance','Assistance / Financial',DROMIC_FIELDS.filter(f=>['Cost of Assistance','Financial Assistance'].includes(f.group)).map(f=>f.key)]]
const GROUP_LABEL={affected_families:'No. of Affected Population',affected_persons:'No. of Affected Population',affected_4ps_families:'No. of Affected Population',evacuation_centers_cum:'No. of Evacuation Centers',evacuation_centers_now:'No. of Evacuation Centers',ec_latitude:'Evacuation Center Details',ec_longitude:'Evacuation Center Details',ec_name:'Evacuation Center Details',ec_address:'Evacuation Center Details',origin_brgy_name:'Origin of IDPs',origin_brgy_count:'Origin of IDPs',inside_families_cum:'Inside ECs',inside_families_now:'Inside ECs',inside_persons_cum:'Inside ECs',inside_persons_now:'Inside ECs',outside_families_cum:'Outside ECs',outside_families_now:'Outside ECs',outside_persons_cum:'Outside ECs',outside_persons_now:'Outside ECs',non_idp_families:'Non-IDPs',non_idp_persons:'Non-IDPs',damaged_totally:'No. of Damaged Houses',damaged_partially:'No. of Damaged Houses',province_served:'Total Cost of Assistance',province_amount:'Total Cost of Assistance',lgu_served:'Total Cost of Assistance',lgu_amount:'Total Cost of Assistance',ngo_amount:'Total Cost of Assistance',others_amount:'Total Cost of Assistance',remarks:'Remarks'}
function shortLabel(f){return f.label.replace(/ — /g,' ').replace('Affected ','').replace('Number of ','').replace('Inside ECs / ','').replace('Outside ECs / ','')}
export default function DromicEntryTable({rows,previous,disabled,onChange}){
 const [tab,setTab]=useState('core');const keys=TABS.find(t=>t[0]===tab)?.[2]||CORE_KEYS;const fields=keys.map(k=>DROMIC_FIELDS.find(f=>f.key===k)).filter(Boolean)
 const groups=useMemo(()=>{const arr=[];for(const f of fields){const g=tab==='core'?(GROUP_LABEL[f.key]||f.group):f.group;const last=arr[arr.length-1];if(last&&last.label===g)last.count++;else arr.push({label:g,count:1})}return arr},[fields,tab])
 const update=(item,key,raw)=>{const field=DROMIC_FIELDS.find(f=>f.key===key);let value=raw;if(field?.kind==='number'||field?.kind==='money')value=raw===''?'':Number(raw);const data={...(item.data||{}),[key]:value};if(field?.computedFrom){const [a,b]=field.computedFrom;data[key]=Number(data[a]||0)*Number(data[b]||0)}onChange({...item,data})}
 return <section className="dromic-table-panel"><div className="dromic-toolbar"><div><span className="eyebrow">Official DROMIC entry</span><h2>DROMIC Reporting Table</h2><p>Excel-style data entry with grouped DROMIC headers, but split into readable sections so LGU focal persons do not face 200+ columns at once.</p></div><div className="table-tabs">{TABS.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{id==='core'?<LayoutGrid size={15}/>:<Rows3 size={15}/>} {label}</button>)}</div></div><div className="dromic-grid-wrap"><table className="dromic-grid"><thead><tr className="group-head"><th className="sticky-col lgu-col" rowSpan="2">Affected Barangay</th>{groups.map((g,i)=><th key={`${g.label}-${i}`} colSpan={g.count}>{g.label}</th>)}</tr><tr className="field-head">{fields.map(f=><th key={f.key} title={f.label}>{shortLabel(f)}</th>)}</tr></thead><tbody>{rows.map(item=>{const issues=validateBarangay(item.data||{},previous[item.barangay_id]||{});return <tr key={item.id}><td className="sticky-col lgu-col"><b>{item.barangays?.name||'Barangay'}</b>{issues.length>0&&<small className="row-issue"><AlertTriangle size={12}/>{issues.length} check{issues.length>1?'s':''}</small>}</td>{fields.map(f=>{const issue=issues.find(i=>i.field===f.key);const val=item.data?.[f.key]??'';return <td key={f.key} className={issue?`grid-cell ${issue.severity.toLowerCase()}`:'grid-cell'}>{f.kind==='textarea'?<textarea disabled={disabled} value={val} onChange={e=>update(item,f.key,e.target.value)} title={issue?.message||f.label}/>:<input disabled={disabled} type={f.kind==='number'||f.kind==='money'?'number':'text'} min={f.kind==='number'||f.kind==='money'?0:undefined} step={f.kind==='money'?'0.01':'1'} value={val} onChange={e=>update(item,f.key,e.target.value)} title={issue?.message||f.label}/>} {issue&&<span className="cell-alert" title={issue.message}>!</span>}</td>})}</tr>})}{!rows.length&&<tr><td colSpan={fields.length+1} className="empty">Add an affected barangay to begin encoding the DROMIC table.</td></tr>}</tbody></table></div></section>
}
