import {NavLink,useNavigate} from 'react-router-dom'
import {LayoutDashboard,FileText,History,Settings,Bell,LogOut,ShieldCheck,Menu,X,UserCheck,FilePlus2,UserRound,MessageCircle,CalendarPlus} from 'lucide-react'
import {useEffect,useState} from 'react'
import {ROLE_LABELS} from '../lib/constants'
import {supabase} from '../lib/supabase'
export default function Layout({profile,children}){
 const [open,setOpen]=useState(false),[unread,setUnread]=useState(0);const nav=useNavigate()
 useEffect(()=>{let channel,timer;async function loadUnread(){const {count}=await supabase.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',profile.id).is('read_at',null);setUnread(count||0)}loadUnread();timer=setInterval(loadUnread,5000);channel=supabase.channel(`notif-${profile.id}`).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`user_id=eq.${profile.id}`},loadUnread).subscribe();return()=>{clearInterval(timer);if(channel)supabase.removeChannel(channel)}},[profile.id])
 const common=[['/notifications','Notifications',Bell],['/chat','Chat',MessageCircle],['/profile','My Profile',UserRound]]
 const items=profile?.role==='lgu'?[['/','Dashboard',LayoutDashboard],['/current-report','Create / Current Report',FilePlus2],['/history','Report History',History],...common]:profile?.role==='viewer'?[['/','Situation Reports',FileText],['/history','Report History',History],...common]:[['/','Provincial Dashboard',LayoutDashboard],['/operations','Incidents & SitRep Setup',CalendarPlus],['/approvals','LGU Approvals',UserCheck],['/sitrep','Situation Reports',FileText],['/history','Report History',History],...common,...(profile?.role==='admin'?[['/admin','System Administration',Settings]]:[])]
 async function logout(){await supabase.auth.signOut();nav('/login')}
 return <div className="app-shell"><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="seal">DR</div><div><b>DROMIC</b><small>Province of Pangasinan</small></div><button className="mobile-close" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="sidebar-stripe"><i></i><i></i><i></i></div><nav>{items.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={18}/><span>{label}</span>{to==='/notifications'&&unread>0&&<em className="nav-count">{unread>99?'99+':unread}</em>}</NavLink>)}</nav><div className="userbox"><div className="mini-avatar">{profile?.avatar_url?<img src={profile.avatar_url}/>:<ShieldCheck size={18}/>}</div><div><b>{profile?.full_name||'User'}</b><small>{ROLE_LABELS[profile?.role]||profile?.role}{profile?.contact_number?'':' • Contact missing'}</small></div><button onClick={logout} title="Sign out"><LogOut size={17}/></button></div></aside><main className="main"><header className="topbar"><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="topbar-copy"><b>{profile?.role==='lgu'?'DROMIC Reporting System':profile?.role==='viewer'?'DROMIC Situation Report Viewer':'Provincial DROMIC Reporting System'}</b><small>{profile?.role==='lgu'?(profile?.requested_lgu_name||'LGU Disaster Reporting Workspace'):profile?.role==='viewer'?'DSWD / PDRRMO Portal':'Provincial Social Welfare and Development Office'}</small></div><span className="live">● Secure session</span></header><div className="tricolor"><span></span><span></span><span></span></div><div className="page">{children}</div></main></div>
}
